name: secretbin
services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=secretbin
      - POSTGRES_DB=secretbin
    volumes:
      - ./postgres/tls/ca.crt:/etc/postgresql/ca.crt
      - ./postgres/tls/server.crt:/etc/postgresql/server.crt
      - ./postgres/tls/server.key:/etc/postgresql/server.key
      - pgdata:/var/lib/postgresql
    command:
      - postgres
      - -c
      - ssl=on
      - -c
      - ssl_ca_file=/etc/postgresql/ca.crt
      - -c
      - ssl_cert_file=/etc/postgresql/server.crt
      - -c
      - ssl_key_file=/etc/postgresql/server.key
    networks:
      - secretbin

  secretbin_arm64:
    image: ghcr.io/secretbin-io/secretbin:latest_arm64
    container_name: secretbin
    read_only: true
    platform: linux/arm64
    environment:
      - SB_DATABASE_HOST=10.0.5.5
    ports:
      - "8001:8000"
    command: ["-unsafely-ignore-certificate-errors"]
    volumes:
      - ../config.yaml:/app/config.yaml
      - ../resources:/app/resources
      - ../public:/app/public
    networks:
      - secretbin

  secretbin_amd64:
    image: ghcr.io/secretbin-io/secretbin:latest_amd64
    container_name: secretbin_amd64
    read_only: true
    platform: linux/amd64
    environment:
      - SB_DATABASE_HOST=10.0.5.5
    ports:
      - "8001:8000"
    volumes:
      - ../config.yaml:/app/config.yaml
      - ../resources:/app/resources
      - ../public:/app/public
    networks:
      - secretbin

volumes:
  pgdata:
