version: 2

project_name: SecretBin

before:
  hooks:
    - deno task icons:generate
    - deno task build
  
builds:
  - builder: deno
    targets:
      - x86_64-pc-windows-msvc
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    main: _fresh/compiled-entry.js
    flags:
      - --include=_fresh
      - --include=static
      - --unstable-cron
      - --allow-all
      - >-
        {{- if eq .Os "windows" -}}
        --icon=resources/Icon.ico
        {{- end -}}

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}
      {{- title .Os }}
      {{- end -}}_
      {{- .Arch }}
    format_overrides:
      - goos: linux
        formats: [tar.gz]
    files:
      - README.md
      - LICENSE
      - config.yaml
      - resources/terms_de.md
      - resources/terms_en.md

dockers_v2:
  - id: secretbin
    dockerfile: Dockerfile
    images: ["ghcr.io/secretbin-io/secretbin"]
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "SecretBin"
      "org.opencontainers.image.authors": "Marvin Peter"
      "org.opencontainers.image.documentation": "{{.GitURL}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.description": "SecretBin is a web app for sharing secrets like tokens and passwords."
    annotations:
      "index:org.opencontainers.image.name": "{{.ProjectName}}"
      "index:org.opencontainers.image.title": "SecretBin"
      "index:org.opencontainers.image.authors": "Marvin Peter"
      "index:org.opencontainers.image.documentation": "{{.GitURL}}"
      "index:org.opencontainers.image.source": "{{.GitURL}}"
      "index:org.opencontainers.image.created": "{{.Date}}"
      "index:org.opencontainers.image.revision": "{{.FullCommit}}"
      "index:org.opencontainers.image.version": "{{.Version}}"
      "index:org.opencontainers.image.licenses": "MIT"
      "index:org.opencontainers.image.description": "SecretBin is a web app for sharing secrets like tokens and passwords."