version: 2

project_name: SecretBin

before:
  hooks:
    - deno task icons:generate
    - deno task build

builds:
  - builder: deno
    targets:
      - x86_64-pc-windows-msvc
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    main: _fresh/compiled-entry.js
    flags:
      - --include=_fresh
      - --include=static
      - --unstable-cron
      - --allow-all
      - >-
        {{- if eq .Os "windows" -}}
        --icon=resources/Icon.ico
        {{- end -}}

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}
      {{- title .Os }}
      {{- end -}}_
      {{- .Arch }}
    format_overrides:
      - goos: linux
        formats: [tar.gz]
    files:
      - README.md
      - LICENSE
      - config.yaml
      - resources/terms_de.md
      - resources/terms_en.md
