banner: # Banner shown at the top of the app. You may use this option for e.g. announcements.
  enabled: false # Show the banner if true
  type: warning # Banner type (info, warning or error)
  text: # Text shown in the banner
    en: This is a preview version. Do not use in production!
    de: Dies ist eine Vorabversion. Keine produktive Nutzung!
branding:
  appName: SecretBin2 # Changes the app in all places including but not limited to the title bar
  footer: SecretBin # Text shown in the footer on the left side e.g. the name of the service hoster
  links: # Custom link shown in the footer on the right
    - name: # Localized display text
        en: Source Code
        de: Quellcode
      link:
        en: https://source.secretbin.io # URL
  showLogo: true # If set the true, the app logo is shown before the app name in the navigation bar
  invertLogo: false # Invert the colors of the app logo in dark mode
  terms: # ToS Dialog show when the user first visits the app (if terms is not specified no dialog is shown)
    title:
      en: Terms of Service
      de: Nutzungsbedingungen
    content: # Text that may contain HTML
      en:
        file: resources/terms_en.md
      de:
        file: resources/terms_de.md
defaults: # Just customizable defaults
  expires: 2w # Default expire time when creating a new secret
  burn: true # Default burn selection
  showPassword: false # Show password box by default
expires: [5min, 1hr, 1d, 1w, 2w, 1m] # Expire options for new secrets
logging:
  level: info # Logging level (default: info)
  mode: text # Specifies if logs should be rendered as text or JSON (default: text)
  logAccess: true # Enable web access logging (default: false)
policy:
  requirePassword: false # Forces users to enable the burn option for new secrets
  requireBurn: false # Forces users to specify a password for new secrets
  denySlowBurn: false # Blocks users from enabling slow burn for new secrets
  encryptionAlgorithm: AES256-GCM # Algorithm used for encrypting new secrets (AES256-GCM, XChaCha20-Poly1305)
  recordEvents: true # Whether to record events such as reads, deletions, and expirations
storage:
  maxSize: 10000M # Max size a new secret is allowed to have
  garbageCollection: # Config the garbage collector which deletes expired secrets
    cron: "0 * * * *" # Configure when the garbage collector should run
  database: # Configure PostgreSQL
    host: 127.0.0.1
    port: 5432
    database: secretbin
    username: secretbin
    password: abc123
    tls: require
