name: secretbin
services:
  secretbin:
    image: ghcr.io/secretbin-io/secretbin:latest-arm64
    container_name: secretbin
    read_only: true
    environment:
      DENO_CERT: /app/certs/ca.crt
      SB_DATABASE_HOST: "postgres"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
      - type: bind
        source: "$PGPATH/tls"
        target: /app/certs
      - type: bind
        source: ./resources
        target: /app/resources
      - type: bind
        source: ./public
        target: /app/public
    extra_hosts:
      - postgres:host-gateway
    networks:
      - secretbin

networks:
  secretbin:
