// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $_middleware from "./routes/_middleware.ts"
import * as $api_config from "./routes/api/config.ts"
import * as $api_secret_id_ from "./routes/api/secret/[id].ts"
import * as $api_secret_index from "./routes/api/secret/index.ts"
import * as $credits from "./routes/credits.tsx"
import * as $index from "./routes/index.tsx"
import * as $manifest_json from "./routes/manifest.json.ts"
import * as $secret_id_delete from "./routes/secret/[id]/delete.tsx"
import * as $secret_id_index from "./routes/secret/[id]/index.tsx"
import * as $secret_id_share from "./routes/secret/[id]/share.tsx"
import * as $DeleteSecret from "./islands/DeleteSecret.tsx"
import * as $Footer from "./islands/Footer.tsx"
import * as $Navbar from "./islands/Navbar.tsx"
import * as $NewSecret from "./islands/NewSecret.tsx"
import * as $ShareSecret from "./islands/ShareSecret.tsx"
import * as $Terms from "./islands/Terms.tsx"
import * as $ViewSecret from "./islands/ViewSecret.tsx"
import * as $mod from "./islands/mod.ts"
import { type Manifest } from "$fresh/server.ts"

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/_middleware.ts": $_middleware,
		"./routes/api/config.ts": $api_config,
		"./routes/api/secret/[id].ts": $api_secret_id_,
		"./routes/api/secret/index.ts": $api_secret_index,
		"./routes/credits.tsx": $credits,
		"./routes/index.tsx": $index,
		"./routes/manifest.json.ts": $manifest_json,
		"./routes/secret/[id]/delete.tsx": $secret_id_delete,
		"./routes/secret/[id]/index.tsx": $secret_id_index,
		"./routes/secret/[id]/share.tsx": $secret_id_share,
	},
	islands: {
		"./islands/DeleteSecret.tsx": $DeleteSecret,
		"./islands/Footer.tsx": $Footer,
		"./islands/Navbar.tsx": $Navbar,
		"./islands/NewSecret.tsx": $NewSecret,
		"./islands/ShareSecret.tsx": $ShareSecret,
		"./islands/Terms.tsx": $Terms,
		"./islands/ViewSecret.tsx": $ViewSecret,
		"./islands/mod.ts": $mod,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
