# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  IMG_PATH: static/images
  SOURCE_URL: https://github.com/secretbin-io/secretbin
  IMG_REPO: ghcr.io/secretbin-io/secretbin

tasks:
  icons:generate:
    desc: Generate all necessary icons based on logo.png
    vars:
      IMAGES:
        - name: android-chrome-192x192.png
          size: 192x192
        - name: android-chrome-512x512.png
          size: 512x512
        - name: apple-touch-icon.png
          size: 180x180
        - name: favicon-16x16.png
          size: 16x16
        - name: favicon-32x32.png
          size: 32x32
    cmds:
      - for: { var: IMAGES }
        cmd: magick {{.IMG_PATH}}/logo.png -resize {{.ITEM.size}} {{.IMG_PATH}}/{{.ITEM.name}}
      - magick {{.IMG_PATH}}/logo.png -define icon:auto-resize=16,32,48 {{.IMG_PATH}}/favicon.ico
      - magick {{.IMG_PATH}}/logo.png -define icon:auto-resize=16,24,32,48,64,72,96,128,256 resources/icon.ico
  release:
    desc: "Build and publish release using GoReleaser"
    cmd: goreleaser release --clean
  snapshot:
    desc: "Build but not release using GoReleaser"
    cmd: goreleaser release --clean --snapshot
  db:start:
    desc: Start the database using docker-compose
    dir: container
    cmd: container-compose up -d postgres
  db:stop:
    desc: Stop the database using docker-compose
    dir: container
    cmds:
      - container-compose down postgres
      - container rm secretbin-postgres
  container:run:*:
    desc: Run the application using docker-compose
    dir: container
    vars:
      ARCH: "{{index .MATCH 0}}"
      CONTAINER: "secretbin_{{.ARCH}}"
    cmds:
      - container build --arch {{.ARCH}} --file Dockerfile --tag {{.IMG_REPO}}:latest_{{.ARCH}} ../dist
      - sh -c 'container-compose up {{.CONTAINER}} &'
      - read
      - pkill -f "container-compose up {{.CONTAINER}}"
      - container-compose down {{.CONTAINER}}
      - container rm {{.CONTAINER}}
  container:release:
    desc: Build and push container image to GitHub Registry
    dir: container
    vars:
      METADATA_JSON: { sh: cat ../dist/metadata.json }
      METADATA: { ref: "fromJson .METADATA_JSON" }
    preconditions:
      - sh: '{{ not (contains "SNAPSHOT" .METADATA.version) }}'
        msg: Cannot release snapshot build. Please run `task release` first
    cmds:
      - |
        container build \
          --arch amd64 \
          --arch arm64 \
          --file Dockerfile \
          --tag {{.IMG_REPO}}:latest \
          --label "org.opencontainers.image.name=secretbin" \
          --label "org.opencontainers.image.title=SecretBin" \
          --label "org.opencontainers.image.authors=Marvin Peter" \
          --label "org.opencontainers.image.documentation={{.SOURCE_URL}}" \
          --label "org.opencontainers.image.source={{.SOURCE_URL}}" \
          --label "org.opencontainers.image.created={{.METADATA.date}}" \
          --label "org.opencontainers.image.revision={{.METADATA.commit}}" \
          --label "org.opencontainers.image.version={{.METADATA.version}}" \
          --label "org.opencontainers.image.licenses=MIT" \
          --label "org.opencontainers.image.description=SecretBin is a web app for sharing secrets like tokens and passwords." \
          ../dist
      - container image tag {{.IMG_REPO}}:latest {{.IMG_REPO}}:{{.METADATA.version}}
      - container image push {{.IMG_REPO}}:latest
      - container image push {{.IMG_REPO}}:{{.METADATA.version}}
